### PR TITLE
Sync more data

### PR DESCRIPTION
**Pull request by notz**
This changes the way data is synced to garmin. It syncs all groups between last sync and now. 
Also it sync all additional fields that has garmin in common with nokia. 

The smashrun sync shouldn't be affected. I havn't tested it.

### CODE REVIEW

**Comment by magnific0** [comment]
@notz thanks the code and submitting the PR. I want to understand your code and test it before merging, so I'll get to this later this week and update here.

**Comment by fernat** [comment]
Did this code get merged? I was going to write code to upload body fat and water data from Nokia to Garmin but suspect @notz additions do it already.

**Comment by magnific0** [comment]
@fernat thanks for reminding me. No it isn't merged. I never got around to testing it and then forgot about it.
The code looks good from what I can tell, so I'll merge it now. However I can't verify it works with the additional data. So could you test this and report back? Thanks

**Comment by fernat** [comment]
@magnific0 Looks good, code appears to be working. I'm seeing historical updates and updates to the body measurements.

**Pull request merged**
